### ISSUE TITLE
package not found - Target of URI doesn't exist

### ISSUE THREAD

**Issue by arizvi-techgies** [gskinner/flutter_animate#115]
I am using the below in my main.dart, I have tried cleaning and rebuilding, closing and reopening the vs code, and uninstalling and reinstalling the package. All other packages are working except this one.

`import 'package:flutter_animate/flutter_animate.dart';`

My pubspec.yaml

```
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  local_auth:
  riverpod:
  flutter_secure_storage:
  flutter_animate: ^4.2.0+1
  material_design_icons_flutter:
  flutter_native_splash:
  http:
  openapi_generator_annotations: ^4.11.0
  flutter_platform_widgets: ^5.0.0
```
Error

```
[{
	"resource": "/Flutter/flutter_app/lib/screens/home/main.dart",
	"owner": "_generated_diagnostic_collection_name_#6",
	"code": {
		"value": "uri_does_not_exist",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/uri_does_not_exist",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "Target of URI doesn't exist: 'package:flutter_animate/flutter_animate.dart'.\nTry creating the file referenced by the URI, or try using a URI for a file that does exist.",
	"source": "dart",
	"startLineNumber": 4,
	"startColumn": 8,
	"endLineNumber": 4,
	"endColumn": 54
}]
```
